apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DatPhan06/top-spring-on-kubernetes.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true